// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.

export const environment = {
  production: true,
  serverUrl: 'https://api.chucknorris.io',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'fr-FR'],
  firebase: {
    apiKey: 'AIzaSyBMNblbSynPnUM-AGL7bcJ-EbjgTZsc798',
    authDomain: 'angular-graphic-drawer.firebaseapp.com',
    databaseURL: 'https://angular-graphic-drawer.firebaseio.com',
    projectId: 'angular-graphic-drawer',
    storageBucket: 'angular-graphic-drawer.appspot.com',
    messagingSenderId: '545035993604'
  }
};
